title: Arctica
baseurl: ""
url: https://exkcd.github.io/arctica

permalink: pretty
plugins:
  - jekyll-seo-tag

exclude:
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock

nav:
  - title: About
    url: /about
