title: Arctica
baseurl: "/"
url: exkcd.github.io/arctica

permalink: pretty
plugins:
  - jekyll-seo-tag

exclude:
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock

kramdown:
  input: GFM
  syntax_highligher: rouge

nav:
  - title: About
    url: /about
